# Generated by Django 5.2.4 on 2025-01-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendance'),
    ]

    operations = [
        # First, create the new models
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1st Sem', '1st Semester'), ('2nd Sem', '2nd Semester')], max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # Add temporary field to preserve academic_year data
        migrations.AddField(
            model_name='course',
            name='academic_year_temp',
            field=models.CharField(max_length=20, null=True),
        ),
        # Add new fields
        migrations.AddField(
            model_name='course',
            name='academic_year_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='attendance.academicyear'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='attendance.semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='default_subjects',
            field=models.ManyToManyField(blank=True, related_name='courses', to='attendance.subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        # Copy data from old field to temp field
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('attendance', 'Course').objects.update(
                academic_year_temp=models.F('academic_year')
            ),
            reverse_code=lambda apps, schema_editor: None,
        ),
        # Remove old field
        migrations.RemoveField(
            model_name='course',
            name='academic_year',
        ),
        # Rename new field to old name
        migrations.RenameField(
            model_name='course',
            old_name='academic_year_new',
            new_name='academic_year',
        ),
        # Update unique constraint
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'academic_year', 'semester', 'supervisor')},
        ),
        # Add ordering
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
    ]
