# Generated by Django 5.2.4 on 2025-07-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_remove_course_academic_year_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentmasterlist',
            name='lrn',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
