# Generated by Django 5.2.4 on 2025-07-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_remove_studentmasterlist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmasterlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentmasterlist',
            name='lrn',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
