# Generated by Django 5.2.4 on 2025-07-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_studentmasterlist_id_alter_studentmasterlist_lrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('student', 'student')], max_length=20),
        ),
    ]
