# Generated by Django 5.2.4 on 2025-07-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmasterlist',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
