# Generated by Django 5.2.4 on 2025-07-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_customuser_role_studentauditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentmasterlist',
            name='lrn',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
