# Generated by Django 5.2.4 on 2025-07-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_remove_studentmasterlist_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmasterlist',
            name='user',
        ),
        migrations.RenameField(
            model_name='studentauditlog',
            old_name='student_lrn',
            new_name='student_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='coursestudent',
            unique_together={('course', 'student')},
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='StudentMasterlist',
        ),
    ]
